apiVersion: apps/v1
kind: Deployment
metadata:
  name: yggdrasil-payment-worker-deployment
  labels:
    app: yggdrasil-payment-worker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yggdrasil-payment-worker-app
  template:
    metadata:
      labels:
        app: yggdrasil-payment-worker-app
    spec:
      containers:
      - name: yggdrasil-payment-worker
        image: hub.dwarvesf.com/yggdrasil/payment:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: SERVICE_ADDRESS
          value: "yggdrasil-payment-worker-service"
        - name: PORT
          value: "3000"
        - name: STRIPE
          valueFrom:
            secretKeyRef:
              name: yggdrasil
              key: stripe
      imagePullSecrets:
      - name: dwarvesf