version: "3.5"
services:

  postgres:
    image: postgres:9.6
    restart: always
    container_name: postgres
    volumes:
      - "./seed.sql:/docker-entrypoint-initdb.d/seed.sql"
    environment:
      POSTGRES_DB: yggdrasil
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    depends_on:
      - registrator
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      service-mesh:
        ipv4_address: 10.5.0.4
  
  postgres-test:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: 123
    expose:
      - "5432"
    ports:
      - "5439:5432"
    networks:
      service-mesh:
        ipv4_address: 10.5.0.100

  kafka:
    image: nats-streaming/latest
    container_name: nats
    ports:
      - "4223:4223"
      - "8223:8223"
    expose:
      - "4223"
      - "8223"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      service-mesh:
        ipv4_address: 10.5.0.6

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8777:8080
    restart: always
    networks:
      service-mesh:
        ipv4_address: 10.5.0.90

networks:
  service-mesh:
    name: service-mesh-nw
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16
