version: "3.5"
services:
  consul:
    image: progrium/consul
    restart: always
    container_name: consul
    command: -server -bootstrap -ui-dir /ui
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    networks:
      service-mesh:
        ipv4_address: 10.5.0.2

  postgres:
    image: postgres:9.6
    restart: always
    container_name: postgres_yggdrasil
    environment:
      POSTGRES_DB: yggdrasil
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      service-mesh:
        ipv4_address: 10.5.0.3
  
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    networks:
      service-mesh:
        ipv4_address: 10.5.0.7

  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.5.0.6
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      service-mesh:
        ipv4_address: 10.5.0.6

  registrator:
    image: gliderlabs/registrator:latest
    restart: always
    container_name: registrator
    command: -ip 10.5.0.5 -cleanup=true  consul://10.5.0.2:8500
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    depends_on:
      - consul
    networks:
      service-mesh:
        ipv4_address: 10.5.0.4

networks:
  service-mesh:
    name: service-mesh-nw
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16