version: '3.5'
services:
  identity:
    image: identity
    container_name: identity
    build:
      context: ${GOPATH}/src/github.com/dwarvesf/yggdrasil/services/identity
    env_file:
      - .env
    external_links:
      - consul:consul-server
      - service_mesh_db
    ports:
      - ${PORT}:${PORT}
    networks:
      service-mesh:
        ipv4_address: 10.5.0.7

networks:
  service-mesh:
    name: service-mesh-nw
