apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: sms
    type: service-mesh
  name: sms
  namespace: sol
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        updatedTimestamp: thurs
      labels:
        app: sms
        type: service-mesh
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: cloud.google.com/gke-preemptible
                operator: Exists
            weight: 100
      containers:
      - name: sms
        image: lmquang/sms
        resources:
          limits:
            memory: "256Mi"
          requests:
            memory: "128Mi"
        imagePullPolicy: Always
      restartPolicy: Always
