version: "3.5"
services:
  organization:
    image: follow
    container_name: follow
    build:
      context: ${GOPATH}/src/github.com/dwarvesf/yggdrasil/follow
    env_file:
      - .env
    external_links:
      - consul:consul-server
      - service_mesh_db
    ports:
      - ${PORT}:${PORT}
    networks:
      service-mesh:
        ipv4_address: ${PRIVATE_IP}

networks:
  service-mesh:
    name: service-mesh-nw
